#!/usr/bin/env bash

set -euo pipefail

function main() {
  ./install-symlinks

  if [ "${1:-}" == "all" ]; then
    qmk-compile "$(list-keyboards)"
  else
    kb="$(pick-keyboard "$@")"
    if [ -z "$kb" ]; then
      echo "No keyboard selected."
      exit 1
    fi
    qmk-compile "$kb"
  fi
}

function list-keyboards() {
  cut -d, -f2 keyboards.cfg
}

function qmk-compile() {
  for kb in "$@"; do
    build-markdown "$kb"
    qmk compile -kb "$kb" -km elentok
    kb_basename="$(echo "$kb" | tr / _)"
    cp -f "$HOME/qmk_firmware/${kb_basename}_elentok".* ./binaries
  done
}

function build-markdown() {
  dir="$(keyboard-dir "$kb")"
  fd layout.md "$dir" | while read -r file; do
    echo "- Building markdown file $file"
    (cd "$(dirname "$file")" && qmkmd build layout.md)
  done
}

function pick-keyboard() {
  list-keyboards | filter "$@" | fzf-tmux -p --select-1
}

function keyboard-dir() {
  grep ",$1\$" keyboards.cfg | cut -d, -f1
}

function filter() {
  if [ $# -eq 0 ]; then
    cat
  else
    grep "$@"
  fi
}

main "$@"
