#!/usr/bin/env bash

set -euo pipefail

if [ "${1:-}" == "-b" ]; then
  ./build hillside/46/0_1
  shift
fi

side="${1:-}"

if [ -z "$side" ]; then
  echo
  echo "Usage: ./flash-hillside [-b] <left|right>"
  echo
  exit 1
fi

qmk flash -bl "avrdude-split-$side" ./binaries/hillside_46_0_1_elentok.hex
