#!/usr/bin/env bash

set -euo pipefail

# https://getreuer.info/posts/keyboards/achordion/index.html

mkdir -p iris-rev8/keymap/features
curl -o iris-rev8/keymap/features/achordion.c https://raw.githubusercontent.com/getreuer/qmk-keymap/main/features/achordion.c
curl -o iris-rev8/keymap/features/achordion.h https://raw.githubusercontent.com/getreuer/qmk-keymap/main/features/achordion.h
