export const KEYCODES = [
  "KC_NO",
  "KC_TRANSPARENT",
  "KC_A",
  "KC_B",
  "KC_C",
  "KC_D",
  "KC_E",
  "KC_F",
  "KC_G",
  "KC_H",
  "KC_I",
  "KC_J",
  "KC_K",
  "KC_L",
  "KC_M",
  "KC_N",
  "KC_O",
  "KC_P",
  "KC_Q",
  "KC_R",
  "KC_S",
  "KC_T",
  "KC_U",
  "KC_V",
  "KC_W",
  "KC_X",
  "KC_Y",
  "KC_Z",
  "KC_1",
  "KC_2",
  "KC_3",
  "KC_4",
  "KC_5",
  "KC_6",
  "KC_7",
  "KC_8",
  "KC_9",
  "KC_0",
  "KC_ENTER",
  "KC_ESCAPE",
  "KC_BACKSPACE",
  "KC_TAB",
  "KC_SPACE",
  "KC_MINUS",
  "KC_EQUAL",
  "KC_LEFT_BRACKET",
  "KC_RIGHT_BRACKET",
  "KC_BACKSLASH",
  "KC_NONUS_HASH",
  "KC_SEMICOLON",
  "KC_QUOTE",
  "KC_GRAVE",
  "KC_COMMA",
  "KC_DOT",
  "KC_SLASH",
  "KC_CAPS_LOCK",
  "KC_F1",
  "KC_F2",
  "KC_F3",
  "KC_F4",
  "KC_F5",
  "KC_F6",
  "KC_F7",
  "KC_F8",
  "KC_F9",
  "KC_F10",
  "KC_F11",
  "KC_F12",
  "KC_PRINT_SCREEN",
  "KC_SCROLL_LOCK",
  "KC_PAUSE",
  "KC_INSERT",
  "KC_HOME",
  "KC_PAGE_UP",
  "KC_DELETE",
  "KC_END",
  "KC_PAGE_DOWN",
  "KC_RIGHT",
  "KC_LEFT",
  "KC_DOWN",
  "KC_UP",
  "KC_NUM_LOCK",
  "KC_KP_SLASH",
  "KC_KP_ASTERISK",
  "KC_KP_MINUS",
  "KC_KP_PLUS",
  "KC_KP_ENTER",
  "KC_KP_1",
  "KC_KP_2",
  "KC_KP_3",
  "KC_KP_4",
  "KC_KP_5",
  "KC_KP_6",
  "KC_KP_7",
  "KC_KP_8",
  "KC_KP_9",
  "KC_KP_0",
  "KC_KP_DOT",
  "KC_NONUS_BACKSLASH",
  "KC_APPLICATION",
  "KC_KB_POWER",
  "KC_KP_EQUAL",
  "KC_F13",
  "KC_F14",
  "KC_F15",
  "KC_F16",
  "KC_F17",
  "KC_F18",
  "KC_F19",
  "KC_F20",
  "KC_F21",
  "KC_F22",
  "KC_F23",
  "KC_F24",
  "KC_EXECUTE",
  "KC_HELP",
  "KC_MENU",
  "KC_SELECT",
  "KC_STOP",
  "KC_AGAIN",
  "KC_UNDO",
  "KC_CUT",
  "KC_COPY",
  "KC_PASTE",
  "KC_FIND",
  "KC_KB_MUTE",
  "KC_KB_VOLUME_UP",
  "KC_KB_VOLUME_DOWN",
  "KC_LOCKING_CAPS_LOCK",
  "KC_LOCKING_NUM_LOCK",
  "KC_LOCKING_SCROLL_LOCK",
  "KC_KP_COMMA",
  "KC_KP_EQUAL_AS400",
  "KC_INTERNATIONAL_1",
  "KC_INTERNATIONAL_2",
  "KC_INTERNATIONAL_3",
  "KC_INTERNATIONAL_4",
  "KC_INTERNATIONAL_5",
  "KC_INTERNATIONAL_6",
  "KC_INTERNATIONAL_7",
  "KC_INTERNATIONAL_8",
  "KC_INTERNATIONAL_9",
  "KC_LANGUAGE_1",
  "KC_LANGUAGE_2",
  "KC_LANGUAGE_3",
  "KC_LANGUAGE_4",
  "KC_LANGUAGE_5",
  "KC_LANGUAGE_6",
  "KC_LANGUAGE_7",
  "KC_LANGUAGE_8",
  "KC_LANGUAGE_9",
  "KC_ALTERNATE_ERASE",
  "KC_SYSTEM_REQUEST",
  "KC_CANCEL",
  "KC_CLEAR",
  "KC_PRIOR",
  "KC_RETURN",
  "KC_SEPARATOR",
  "KC_OUT",
  "KC_OPER",
  "KC_CLEAR_AGAIN",
  "KC_CRSEL",
  "KC_EXSEL",
  "KC_SYSTEM_POWER",
  "KC_SYSTEM_SLEEP",
  "KC_SYSTEM_WAKE",
  "KC_AUDIO_MUTE",
  "KC_AUDIO_VOL_UP",
  "KC_AUDIO_VOL_DOWN",
  "KC_MEDIA_NEXT_TRACK",
  "KC_MEDIA_PREV_TRACK",
  "KC_MEDIA_STOP",
  "KC_MEDIA_PLAY_PAUSE",
  "KC_MEDIA_SELECT",
  "KC_MEDIA_EJECT",
  "KC_MAIL",
  "KC_CALCULATOR",
  "KC_MY_COMPUTER",
  "KC_WWW_SEARCH",
  "KC_WWW_HOME",
  "KC_WWW_BACK",
  "KC_WWW_FORWARD",
  "KC_WWW_STOP",
  "KC_WWW_REFRESH",
  "KC_WWW_FAVORITES",
  "KC_MEDIA_FAST_FORWARD",
  "KC_MEDIA_REWIND",
  "KC_BRIGHTNESS_UP",
  "KC_BRIGHTNESS_DOWN",
  "KC_CONTROL_PANEL",
  "KC_ASSISTANT",
  "KC_MISSION_CONTROL",
  "KC_LAUNCHPAD",
  "KC_MS_UP",
  "KC_MS_DOWN",
  "KC_MS_LEFT",
  "KC_MS_RIGHT",
  "KC_MS_BTN1",
  "KC_MS_BTN2",
  "KC_MS_BTN3",
  "KC_MS_BTN4",
  "KC_MS_BTN5",
  "KC_MS_BTN6",
  "KC_MS_BTN7",
  "KC_MS_BTN8",
  "KC_MS_WH_UP",
  "KC_MS_WH_DOWN",
  "KC_MS_WH_LEFT",
  "KC_MS_WH_RIGHT",
  "KC_MS_ACCEL0",
  "KC_MS_ACCEL1",
  "KC_MS_ACCEL2",
  "KC_LEFT_CTRL",
  "KC_LEFT_SHIFT",
  "KC_LEFT_ALT",
  "KC_LEFT_GUI",
  "KC_RIGHT_CTRL",
  "KC_RIGHT_SHIFT",
  "KC_RIGHT_ALT",
  "KC_RIGHT_GUI",
  "QK_SWAP_HANDS_TOGGLE",
  "QK_SWAP_HANDS_TAP_TOGGLE",
  "QK_SWAP_HANDS_MOMENTARY_ON",
  "QK_SWAP_HANDS_MOMENTARY_OFF",
  "QK_SWAP_HANDS_OFF",
  "QK_SWAP_HANDS_ON",
  "QK_SWAP_HANDS_ONE_SHOT",
  "QK_MAGIC_SWAP_CONTROL_CAPS_LOCK",
  "QK_MAGIC_UNSWAP_CONTROL_CAPS_LOCK",
  "QK_MAGIC_TOGGLE_CONTROL_CAPS_LOCK",
  "QK_MAGIC_CAPS_LOCK_AS_CONTROL_OFF",
  "QK_MAGIC_CAPS_LOCK_AS_CONTROL_ON",
  "QK_MAGIC_SWAP_LALT_LGUI",
  "QK_MAGIC_UNSWAP_LALT_LGUI",
  "QK_MAGIC_SWAP_RALT_RGUI",
  "QK_MAGIC_UNSWAP_RALT_RGUI",
  "QK_MAGIC_GUI_ON",
  "QK_MAGIC_GUI_OFF",
  "QK_MAGIC_TOGGLE_GUI",
  "QK_MAGIC_SWAP_GRAVE_ESC",
  "QK_MAGIC_UNSWAP_GRAVE_ESC",
  "QK_MAGIC_SWAP_BACKSLASH_BACKSPACE",
  "QK_MAGIC_UNSWAP_BACKSLASH_BACKSPACE",
  "QK_MAGIC_TOGGLE_BACKSLASH_BACKSPACE",
  "QK_MAGIC_NKRO_ON",
  "QK_MAGIC_NKRO_OFF",
  "QK_MAGIC_TOGGLE_NKRO",
  "QK_MAGIC_SWAP_ALT_GUI",
  "QK_MAGIC_UNSWAP_ALT_GUI",
  "QK_MAGIC_TOGGLE_ALT_GUI",
  "QK_MAGIC_SWAP_LCTL_LGUI",
  "QK_MAGIC_UNSWAP_LCTL_LGUI",
  "QK_MAGIC_SWAP_RCTL_RGUI",
  "QK_MAGIC_UNSWAP_RCTL_RGUI",
  "QK_MAGIC_SWAP_CTL_GUI",
  "QK_MAGIC_UNSWAP_CTL_GUI",
  "QK_MAGIC_TOGGLE_CTL_GUI",
  "QK_MAGIC_EE_HANDS_LEFT",
  "QK_MAGIC_EE_HANDS_RIGHT",
  "QK_MAGIC_SWAP_ESCAPE_CAPS_LOCK",
  "QK_MAGIC_UNSWAP_ESCAPE_CAPS_LOCK",
  "QK_MAGIC_TOGGLE_ESCAPE_CAPS_LOCK",
  "QK_MIDI_ON",
  "QK_MIDI_OFF",
  "QK_MIDI_TOGGLE",
  "QK_MIDI_NOTE_C_0",
  "QK_MIDI_NOTE_C_SHARP_0",
  "QK_MIDI_NOTE_D_0",
  "QK_MIDI_NOTE_D_SHARP_0",
  "QK_MIDI_NOTE_E_0",
  "QK_MIDI_NOTE_F_0",
  "QK_MIDI_NOTE_F_SHARP_0",
  "QK_MIDI_NOTE_G_0",
  "QK_MIDI_NOTE_G_SHARP_0",
  "QK_MIDI_NOTE_A_0",
  "QK_MIDI_NOTE_A_SHARP_0",
  "QK_MIDI_NOTE_B_0",
  "QK_MIDI_NOTE_C_1",
  "QK_MIDI_NOTE_C_SHARP_1",
  "QK_MIDI_NOTE_D_1",
  "QK_MIDI_NOTE_D_SHARP_1",
  "QK_MIDI_NOTE_E_1",
  "QK_MIDI_NOTE_F_1",
  "QK_MIDI_NOTE_F_SHARP_1",
  "QK_MIDI_NOTE_G_1",
  "QK_MIDI_NOTE_G_SHARP_1",
  "QK_MIDI_NOTE_A_1",
  "QK_MIDI_NOTE_A_SHARP_1",
  "QK_MIDI_NOTE_B_1",
  "QK_MIDI_NOTE_C_2",
  "QK_MIDI_NOTE_C_SHARP_2",
  "QK_MIDI_NOTE_D_2",
  "QK_MIDI_NOTE_D_SHARP_2",
  "QK_MIDI_NOTE_E_2",
  "QK_MIDI_NOTE_F_2",
  "QK_MIDI_NOTE_F_SHARP_2",
  "QK_MIDI_NOTE_G_2",
  "QK_MIDI_NOTE_G_SHARP_2",
  "QK_MIDI_NOTE_A_2",
  "QK_MIDI_NOTE_A_SHARP_2",
  "QK_MIDI_NOTE_B_2",
  "QK_MIDI_NOTE_C_3",
  "QK_MIDI_NOTE_C_SHARP_3",
  "QK_MIDI_NOTE_D_3",
  "QK_MIDI_NOTE_D_SHARP_3",
  "QK_MIDI_NOTE_E_3",
  "QK_MIDI_NOTE_F_3",
  "QK_MIDI_NOTE_F_SHARP_3",
  "QK_MIDI_NOTE_G_3",
  "QK_MIDI_NOTE_G_SHARP_3",
  "QK_MIDI_NOTE_A_3",
  "QK_MIDI_NOTE_A_SHARP_3",
  "QK_MIDI_NOTE_B_3",
  "QK_MIDI_NOTE_C_4",
  "QK_MIDI_NOTE_C_SHARP_4",
  "QK_MIDI_NOTE_D_4",
  "QK_MIDI_NOTE_D_SHARP_4",
  "QK_MIDI_NOTE_E_4",
  "QK_MIDI_NOTE_F_4",
  "QK_MIDI_NOTE_F_SHARP_4",
  "QK_MIDI_NOTE_G_4",
  "QK_MIDI_NOTE_G_SHARP_4",
  "QK_MIDI_NOTE_A_4",
  "QK_MIDI_NOTE_A_SHARP_4",
  "QK_MIDI_NOTE_B_4",
  "QK_MIDI_NOTE_C_5",
  "QK_MIDI_NOTE_C_SHARP_5",
  "QK_MIDI_NOTE_D_5",
  "QK_MIDI_NOTE_D_SHARP_5",
  "QK_MIDI_NOTE_E_5",
  "QK_MIDI_NOTE_F_5",
  "QK_MIDI_NOTE_F_SHARP_5",
  "QK_MIDI_NOTE_G_5",
  "QK_MIDI_NOTE_G_SHARP_5",
  "QK_MIDI_NOTE_A_5",
  "QK_MIDI_NOTE_A_SHARP_5",
  "QK_MIDI_NOTE_B_5",
  "QK_MIDI_OCTAVE_N2",
  "QK_MIDI_OCTAVE_N1",
  "QK_MIDI_OCTAVE_0",
  "QK_MIDI_OCTAVE_1",
  "QK_MIDI_OCTAVE_2",
  "QK_MIDI_OCTAVE_3",
  "QK_MIDI_OCTAVE_4",
  "QK_MIDI_OCTAVE_5",
  "QK_MIDI_OCTAVE_6",
  "QK_MIDI_OCTAVE_7",
  "QK_MIDI_OCTAVE_DOWN",
  "QK_MIDI_OCTAVE_UP",
  "QK_MIDI_TRANSPOSE_N6",
  "QK_MIDI_TRANSPOSE_N5",
  "QK_MIDI_TRANSPOSE_N4",
  "QK_MIDI_TRANSPOSE_N3",
  "QK_MIDI_TRANSPOSE_N2",
  "QK_MIDI_TRANSPOSE_N1",
  "QK_MIDI_TRANSPOSE_0",
  "QK_MIDI_TRANSPOSE_1",
  "QK_MIDI_TRANSPOSE_2",
  "QK_MIDI_TRANSPOSE_3",
  "QK_MIDI_TRANSPOSE_4",
  "QK_MIDI_TRANSPOSE_5",
  "QK_MIDI_TRANSPOSE_6",
  "QK_MIDI_TRANSPOSE_DOWN",
  "QK_MIDI_TRANSPOSE_UP",
  "QK_MIDI_VELOCITY_0",
  "QK_MIDI_VELOCITY_1",
  "QK_MIDI_VELOCITY_2",
  "QK_MIDI_VELOCITY_3",
  "QK_MIDI_VELOCITY_4",
  "QK_MIDI_VELOCITY_5",
  "QK_MIDI_VELOCITY_6",
  "QK_MIDI_VELOCITY_7",
  "QK_MIDI_VELOCITY_8",
  "QK_MIDI_VELOCITY_9",
  "QK_MIDI_VELOCITY_10",
  "QK_MIDI_VELOCITY_DOWN",
  "QK_MIDI_VELOCITY_UP",
  "QK_MIDI_CHANNEL_1",
  "QK_MIDI_CHANNEL_2",
  "QK_MIDI_CHANNEL_3",
  "QK_MIDI_CHANNEL_4",
  "QK_MIDI_CHANNEL_5",
  "QK_MIDI_CHANNEL_6",
  "QK_MIDI_CHANNEL_7",
  "QK_MIDI_CHANNEL_8",
  "QK_MIDI_CHANNEL_9",
  "QK_MIDI_CHANNEL_10",
  "QK_MIDI_CHANNEL_11",
  "QK_MIDI_CHANNEL_12",
  "QK_MIDI_CHANNEL_13",
  "QK_MIDI_CHANNEL_14",
  "QK_MIDI_CHANNEL_15",
  "QK_MIDI_CHANNEL_16",
  "QK_MIDI_CHANNEL_DOWN",
  "QK_MIDI_CHANNEL_UP",
  "QK_MIDI_ALL_NOTES_OFF",
  "QK_MIDI_SUSTAIN",
  "QK_MIDI_PORTAMENTO",
  "QK_MIDI_SOSTENUTO",
  "QK_MIDI_SOFT",
  "QK_MIDI_LEGATO",
  "QK_MIDI_MODULATION",
  "QK_MIDI_MODULATION_SPEED_DOWN",
  "QK_MIDI_MODULATION_SPEED_UP",
  "QK_MIDI_PITCH_BEND_DOWN",
  "QK_MIDI_PITCH_BEND_UP",
  "QK_SEQUENCER_ON",
  "QK_SEQUENCER_OFF",
  "QK_SEQUENCER_TOGGLE",
  "QK_SEQUENCER_TEMPO_DOWN",
  "QK_SEQUENCER_TEMPO_UP",
  "QK_SEQUENCER_RESOLUTION_DOWN",
  "QK_SEQUENCER_RESOLUTION_UP",
  "QK_SEQUENCER_STEPS_ALL",
  "QK_SEQUENCER_STEPS_CLEAR",
  "QK_JOYSTICK_BUTTON_0",
  "QK_JOYSTICK_BUTTON_1",
  "QK_JOYSTICK_BUTTON_2",
  "QK_JOYSTICK_BUTTON_3",
  "QK_JOYSTICK_BUTTON_4",
  "QK_JOYSTICK_BUTTON_5",
  "QK_JOYSTICK_BUTTON_6",
  "QK_JOYSTICK_BUTTON_7",
  "QK_JOYSTICK_BUTTON_8",
  "QK_JOYSTICK_BUTTON_9",
  "QK_JOYSTICK_BUTTON_10",
  "QK_JOYSTICK_BUTTON_11",
  "QK_JOYSTICK_BUTTON_12",
  "QK_JOYSTICK_BUTTON_13",
  "QK_JOYSTICK_BUTTON_14",
  "QK_JOYSTICK_BUTTON_15",
  "QK_JOYSTICK_BUTTON_16",
  "QK_JOYSTICK_BUTTON_17",
  "QK_JOYSTICK_BUTTON_18",
  "QK_JOYSTICK_BUTTON_19",
  "QK_JOYSTICK_BUTTON_20",
  "QK_JOYSTICK_BUTTON_21",
  "QK_JOYSTICK_BUTTON_22",
  "QK_JOYSTICK_BUTTON_23",
  "QK_JOYSTICK_BUTTON_24",
  "QK_JOYSTICK_BUTTON_25",
  "QK_JOYSTICK_BUTTON_26",
  "QK_JOYSTICK_BUTTON_27",
  "QK_JOYSTICK_BUTTON_28",
  "QK_JOYSTICK_BUTTON_29",
  "QK_JOYSTICK_BUTTON_30",
  "QK_JOYSTICK_BUTTON_31",
  "QK_PROGRAMMABLE_BUTTON_1",
  "QK_PROGRAMMABLE_BUTTON_2",
  "QK_PROGRAMMABLE_BUTTON_3",
  "QK_PROGRAMMABLE_BUTTON_4",
  "QK_PROGRAMMABLE_BUTTON_5",
  "QK_PROGRAMMABLE_BUTTON_6",
  "QK_PROGRAMMABLE_BUTTON_7",
  "QK_PROGRAMMABLE_BUTTON_8",
  "QK_PROGRAMMABLE_BUTTON_9",
  "QK_PROGRAMMABLE_BUTTON_10",
  "QK_PROGRAMMABLE_BUTTON_11",
  "QK_PROGRAMMABLE_BUTTON_12",
  "QK_PROGRAMMABLE_BUTTON_13",
  "QK_PROGRAMMABLE_BUTTON_14",
  "QK_PROGRAMMABLE_BUTTON_15",
  "QK_PROGRAMMABLE_BUTTON_16",
  "QK_PROGRAMMABLE_BUTTON_17",
  "QK_PROGRAMMABLE_BUTTON_18",
  "QK_PROGRAMMABLE_BUTTON_19",
  "QK_PROGRAMMABLE_BUTTON_20",
  "QK_PROGRAMMABLE_BUTTON_21",
  "QK_PROGRAMMABLE_BUTTON_22",
  "QK_PROGRAMMABLE_BUTTON_23",
  "QK_PROGRAMMABLE_BUTTON_24",
  "QK_PROGRAMMABLE_BUTTON_25",
  "QK_PROGRAMMABLE_BUTTON_26",
  "QK_PROGRAMMABLE_BUTTON_27",
  "QK_PROGRAMMABLE_BUTTON_28",
  "QK_PROGRAMMABLE_BUTTON_29",
  "QK_PROGRAMMABLE_BUTTON_30",
  "QK_PROGRAMMABLE_BUTTON_31",
  "QK_PROGRAMMABLE_BUTTON_32",
  "QK_AUDIO_ON",
  "QK_AUDIO_OFF",
  "QK_AUDIO_TOGGLE",
  "QK_AUDIO_CLICKY_TOGGLE",
  "QK_AUDIO_CLICKY_ON",
  "QK_AUDIO_CLICKY_OFF",
  "QK_AUDIO_CLICKY_UP",
  "QK_AUDIO_CLICKY_DOWN",
  "QK_AUDIO_CLICKY_RESET",
  "QK_MUSIC_ON",
  "QK_MUSIC_OFF",
  "QK_MUSIC_TOGGLE",
  "QK_MUSIC_MODE_NEXT",
  "QK_AUDIO_VOICE_NEXT",
  "QK_AUDIO_VOICE_PREVIOUS",
  "QK_STENO_BOLT",
  "QK_STENO_GEMINI",
  "QK_STENO_COMB",
  "QK_STENO_COMB_MAX",
  "QK_MACRO_0",
  "QK_MACRO_1",
  "QK_MACRO_2",
  "QK_MACRO_3",
  "QK_MACRO_4",
  "QK_MACRO_5",
  "QK_MACRO_6",
  "QK_MACRO_7",
  "QK_MACRO_8",
  "QK_MACRO_9",
  "QK_MACRO_10",
  "QK_MACRO_11",
  "QK_MACRO_12",
  "QK_MACRO_13",
  "QK_MACRO_14",
  "QK_MACRO_15",
  "QK_MACRO_16",
  "QK_MACRO_17",
  "QK_MACRO_18",
  "QK_MACRO_19",
  "QK_MACRO_20",
  "QK_MACRO_21",
  "QK_MACRO_22",
  "QK_MACRO_23",
  "QK_MACRO_24",
  "QK_MACRO_25",
  "QK_MACRO_26",
  "QK_MACRO_27",
  "QK_MACRO_28",
  "QK_MACRO_29",
  "QK_MACRO_30",
  "QK_MACRO_31",
  "QK_BACKLIGHT_ON",
  "QK_BACKLIGHT_OFF",
  "QK_BACKLIGHT_TOGGLE",
  "QK_BACKLIGHT_DOWN",
  "QK_BACKLIGHT_UP",
  "QK_BACKLIGHT_STEP",
  "QK_BACKLIGHT_TOGGLE_BREATHING",
  "RGB_TOG",
  "RGB_MODE_FORWARD",
  "RGB_MODE_REVERSE",
  "RGB_HUI",
  "RGB_HUD",
  "RGB_SAI",
  "RGB_SAD",
  "RGB_VAI",
  "RGB_VAD",
  "RGB_SPI",
  "RGB_SPD",
  "RGB_MODE_PLAIN",
  "RGB_MODE_BREATHE",
  "RGB_MODE_RAINBOW",
  "RGB_MODE_SWIRL",
  "RGB_MODE_SNAKE",
  "RGB_MODE_KNIGHT",
  "RGB_MODE_XMAS",
  "RGB_MODE_GRADIENT",
  "RGB_MODE_RGBTEST",
  "RGB_MODE_TWINKLE",
  "QK_BOOTLOADER",
  "QK_REBOOT",
  "QK_DEBUG_TOGGLE",
  "QK_CLEAR_EEPROM",
  "QK_MAKE",
  "QK_AUTO_SHIFT_DOWN",
  "QK_AUTO_SHIFT_UP",
  "QK_AUTO_SHIFT_REPORT",
  "QK_AUTO_SHIFT_ON",
  "QK_AUTO_SHIFT_OFF",
  "QK_AUTO_SHIFT_TOGGLE",
  "QK_GRAVE_ESCAPE",
  "QK_VELOCIKEY_TOGGLE",
  "QK_SPACE_CADET_LEFT_CTRL_PARENTHESIS_OPEN",
  "QK_SPACE_CADET_RIGHT_CTRL_PARENTHESIS_CLOSE",
  "QK_SPACE_CADET_LEFT_SHIFT_PARENTHESIS_OPEN",
  "QK_SPACE_CADET_RIGHT_SHIFT_PARENTHESIS_CLOSE",
  "QK_SPACE_CADET_LEFT_ALT_PARENTHESIS_OPEN",
  "QK_SPACE_CADET_RIGHT_ALT_PARENTHESIS_CLOSE",
  "QK_SPACE_CADET_RIGHT_SHIFT_ENTER",
  "QK_OUTPUT_AUTO",
  "QK_OUTPUT_USB",
  "QK_OUTPUT_BLUETOOTH",
  "QK_UNICODE_MODE_NEXT",
  "QK_UNICODE_MODE_PREVIOUS",
  "QK_UNICODE_MODE_MACOS",
  "QK_UNICODE_MODE_LINUX",
  "QK_UNICODE_MODE_WINDOWS",
  "QK_UNICODE_MODE_BSD",
  "QK_UNICODE_MODE_WINCOMPOSE",
  "QK_UNICODE_MODE_EMACS",
  "QK_HAPTIC_ON",
  "QK_HAPTIC_OFF",
  "QK_HAPTIC_TOGGLE",
  "QK_HAPTIC_RESET",
  "QK_HAPTIC_FEEDBACK_TOGGLE",
  "QK_HAPTIC_BUZZ_TOGGLE",
  "QK_HAPTIC_MODE_NEXT",
  "QK_HAPTIC_MODE_PREVIOUS",
  "QK_HAPTIC_CONTINUOUS_TOGGLE",
  "QK_HAPTIC_CONTINUOUS_UP",
  "QK_HAPTIC_CONTINUOUS_DOWN",
  "QK_HAPTIC_DWELL_UP",
  "QK_HAPTIC_DWELL_DOWN",
  "QK_COMBO_ON",
  "QK_COMBO_OFF",
  "QK_COMBO_TOGGLE",
  "QK_DYNAMIC_MACRO_RECORD_START_1",
  "QK_DYNAMIC_MACRO_RECORD_START_2",
  "QK_DYNAMIC_MACRO_RECORD_STOP",
  "QK_DYNAMIC_MACRO_PLAY_1",
  "QK_DYNAMIC_MACRO_PLAY_2",
  "QK_LEADER",
  "QK_LOCK",
  "QK_ONE_SHOT_ON",
  "QK_ONE_SHOT_OFF",
  "QK_ONE_SHOT_TOGGLE",
  "QK_KEY_OVERRIDE_TOGGLE",
  "QK_KEY_OVERRIDE_ON",
  "QK_KEY_OVERRIDE_OFF",
  "QK_SECURE_LOCK",
  "QK_SECURE_UNLOCK",
  "QK_SECURE_TOGGLE",
  "QK_SECURE_REQUEST",
  "QK_DYNAMIC_TAPPING_TERM_PRINT",
  "QK_DYNAMIC_TAPPING_TERM_UP",
  "QK_DYNAMIC_TAPPING_TERM_DOWN",
  "QK_CAPS_WORD_TOGGLE",
  "QK_AUTOCORRECT_ON",
  "QK_AUTOCORRECT_OFF",
  "QK_AUTOCORRECT_TOGGLE",
  "QK_TRI_LAYER_LOWER",
  "QK_TRI_LAYER_UPPER",
  "QK_REPEAT_KEY",
  "QK_ALT_REPEAT_KEY",
  "QK_KB_0",
  "QK_KB_1",
  "QK_KB_2",
  "QK_KB_3",
  "QK_KB_4",
  "QK_KB_5",
  "QK_KB_6",
  "QK_KB_7",
  "QK_KB_8",
  "QK_KB_9",
  "QK_KB_10",
  "QK_KB_11",
  "QK_KB_12",
  "QK_KB_13",
  "QK_KB_14",
  "QK_KB_15",
  "QK_KB_16",
  "QK_KB_17",
  "QK_KB_18",
  "QK_KB_19",
  "QK_KB_20",
  "QK_KB_21",
  "QK_KB_22",
  "QK_KB_23",
  "QK_KB_24",
  "QK_KB_25",
  "QK_KB_26",
  "QK_KB_27",
  "QK_KB_28",
  "QK_KB_29",
  "QK_KB_30",
  "QK_KB_31",
  "QK_USER_0",
  "QK_USER_1",
  "QK_USER_2",
  "QK_USER_3",
  "QK_USER_4",
  "QK_USER_5",
  "QK_USER_6",
  "QK_USER_7",
  "QK_USER_8",
  "QK_USER_9",
  "QK_USER_10",
  "QK_USER_11",
  "QK_USER_12",
  "QK_USER_13",
  "QK_USER_14",
  "QK_USER_15",
  "QK_USER_16",
  "QK_USER_17",
  "QK_USER_18",
  "QK_USER_19",
  "QK_USER_20",
  "QK_USER_21",
  "QK_USER_22",
  "QK_USER_23",
  "QK_USER_24",
  "QK_USER_25",
  "QK_USER_26",
  "QK_USER_27",
  "QK_USER_28",
  "QK_USER_29",
  "QK_USER_30",
  "QK_USER_31",
  "XXXXXXX", // alias of KC_NO
  "_______", // alias of KC_TRANSPARENT
  "KC_TRNS", // alias of KC_TRANSPARENT
  "KC_ENT", // alias of KC_ENTER
  "KC_ESC", // alias of KC_ESCAPE
  "KC_BSPC", // alias of KC_BACKSPACE
  "KC_SPC", // alias of KC_SPACE
  "KC_MINS", // alias of KC_MINUS
  "KC_EQL", // alias of KC_EQUAL
  "KC_LBRC", // alias of KC_LEFT_BRACKET
  "KC_RBRC", // alias of KC_RIGHT_BRACKET
  "KC_BSLS", // alias of KC_BACKSLASH
  "KC_NUHS", // alias of KC_NONUS_HASH
  "KC_SCLN", // alias of KC_SEMICOLON
  "KC_QUOT", // alias of KC_QUOTE
  "KC_GRV", // alias of KC_GRAVE
  "KC_COMM", // alias of KC_COMMA
  "KC_SLSH", // alias of KC_SLASH
  "KC_CAPS", // alias of KC_CAPS_LOCK
  "KC_PSCR", // alias of KC_PRINT_SCREEN
  "KC_SCRL", // alias of KC_SCROLL_LOCK
  "KC_BRMD", // alias of KC_SCROLL_LOCK
  "KC_PAUS", // alias of KC_PAUSE
  "KC_BRK", // alias of KC_PAUSE
  "KC_BRMU", // alias of KC_PAUSE
  "KC_INS", // alias of KC_INSERT
  "KC_PGUP", // alias of KC_PAGE_UP
  "KC_DEL", // alias of KC_DELETE
  "KC_PGDN", // alias of KC_PAGE_DOWN
  "KC_RGHT", // alias of KC_RIGHT
  "KC_NUM", // alias of KC_NUM_LOCK
  "KC_PSLS", // alias of KC_KP_SLASH
  "KC_PAST", // alias of KC_KP_ASTERISK
  "KC_PMNS", // alias of KC_KP_MINUS
  "KC_PPLS", // alias of KC_KP_PLUS
  "KC_PENT", // alias of KC_KP_ENTER
  "KC_P1", // alias of KC_KP_1
  "KC_P2", // alias of KC_KP_2
  "KC_P3", // alias of KC_KP_3
  "KC_P4", // alias of KC_KP_4
  "KC_P5", // alias of KC_KP_5
  "KC_P6", // alias of KC_KP_6
  "KC_P7", // alias of KC_KP_7
  "KC_P8", // alias of KC_KP_8
  "KC_P9", // alias of KC_KP_9
  "KC_P0", // alias of KC_KP_0
  "KC_PDOT", // alias of KC_KP_DOT
  "KC_NUBS", // alias of KC_NONUS_BACKSLASH
  "KC_APP", // alias of KC_APPLICATION
  "KC_PEQL", // alias of KC_KP_EQUAL
  "KC_EXEC", // alias of KC_EXECUTE
  "KC_SLCT", // alias of KC_SELECT
  "KC_AGIN", // alias of KC_AGAIN
  "KC_PSTE", // alias of KC_PASTE
  "KC_LCAP", // alias of KC_LOCKING_CAPS_LOCK
  "KC_LNUM", // alias of KC_LOCKING_NUM_LOCK
  "KC_LSCR", // alias of KC_LOCKING_SCROLL_LOCK
  "KC_PCMM", // alias of KC_KP_COMMA
  "KC_INT1", // alias of KC_INTERNATIONAL_1
  "KC_INT2", // alias of KC_INTERNATIONAL_2
  "KC_INT3", // alias of KC_INTERNATIONAL_3
  "KC_INT4", // alias of KC_INTERNATIONAL_4
  "KC_INT5", // alias of KC_INTERNATIONAL_5
  "KC_INT6", // alias of KC_INTERNATIONAL_6
  "KC_INT7", // alias of KC_INTERNATIONAL_7
  "KC_INT8", // alias of KC_INTERNATIONAL_8
  "KC_INT9", // alias of KC_INTERNATIONAL_9
  "KC_LNG1", // alias of KC_LANGUAGE_1
  "KC_LNG2", // alias of KC_LANGUAGE_2
  "KC_LNG3", // alias of KC_LANGUAGE_3
  "KC_LNG4", // alias of KC_LANGUAGE_4
  "KC_LNG5", // alias of KC_LANGUAGE_5
  "KC_LNG6", // alias of KC_LANGUAGE_6
  "KC_LNG7", // alias of KC_LANGUAGE_7
  "KC_LNG8", // alias of KC_LANGUAGE_8
  "KC_LNG9", // alias of KC_LANGUAGE_9
  "KC_ERAS", // alias of KC_ALTERNATE_ERASE
  "KC_SYRQ", // alias of KC_SYSTEM_REQUEST
  "KC_CNCL", // alias of KC_CANCEL
  "KC_CLR", // alias of KC_CLEAR
  "KC_PRIR", // alias of KC_PRIOR
  "KC_RETN", // alias of KC_RETURN
  "KC_SEPR", // alias of KC_SEPARATOR
  "KC_CLAG", // alias of KC_CLEAR_AGAIN
  "KC_CRSL", // alias of KC_CRSEL
  "KC_EXSL", // alias of KC_EXSEL
  "KC_PWR", // alias of KC_SYSTEM_POWER
  "KC_SLEP", // alias of KC_SYSTEM_SLEEP
  "KC_WAKE", // alias of KC_SYSTEM_WAKE
  "KC_MUTE", // alias of KC_AUDIO_MUTE
  "KC_VOLU", // alias of KC_AUDIO_VOL_UP
  "KC_VOLD", // alias of KC_AUDIO_VOL_DOWN
  "KC_MNXT", // alias of KC_MEDIA_NEXT_TRACK
  "KC_MPRV", // alias of KC_MEDIA_PREV_TRACK
  "KC_MSTP", // alias of KC_MEDIA_STOP
  "KC_MPLY", // alias of KC_MEDIA_PLAY_PAUSE
  "KC_MSEL", // alias of KC_MEDIA_SELECT
  "KC_EJCT", // alias of KC_MEDIA_EJECT
  "KC_CALC", // alias of KC_CALCULATOR
  "KC_MYCM", // alias of KC_MY_COMPUTER
  "KC_WSCH", // alias of KC_WWW_SEARCH
  "KC_WHOM", // alias of KC_WWW_HOME
  "KC_WBAK", // alias of KC_WWW_BACK
  "KC_WFWD", // alias of KC_WWW_FORWARD
  "KC_WSTP", // alias of KC_WWW_STOP
  "KC_WREF", // alias of KC_WWW_REFRESH
  "KC_WFAV", // alias of KC_WWW_FAVORITES
  "KC_MFFD", // alias of KC_MEDIA_FAST_FORWARD
  "KC_MRWD", // alias of KC_MEDIA_REWIND
  "KC_BRIU", // alias of KC_BRIGHTNESS_UP
  "KC_BRID", // alias of KC_BRIGHTNESS_DOWN
  "KC_CPNL", // alias of KC_CONTROL_PANEL
  "KC_ASST", // alias of KC_ASSISTANT
  "KC_MCTL", // alias of KC_MISSION_CONTROL
  "KC_LPAD", // alias of KC_LAUNCHPAD
  "KC_MS_U", // alias of KC_MS_UP
  "KC_MS_D", // alias of KC_MS_DOWN
  "KC_MS_L", // alias of KC_MS_LEFT
  "KC_MS_R", // alias of KC_MS_RIGHT
  "KC_BTN1", // alias of KC_MS_BTN1
  "KC_BTN2", // alias of KC_MS_BTN2
  "KC_BTN3", // alias of KC_MS_BTN3
  "KC_BTN4", // alias of KC_MS_BTN4
  "KC_BTN5", // alias of KC_MS_BTN5
  "KC_BTN6", // alias of KC_MS_BTN6
  "KC_BTN7", // alias of KC_MS_BTN7
  "KC_BTN8", // alias of KC_MS_BTN8
  "KC_WH_U", // alias of KC_MS_WH_UP
  "KC_WH_D", // alias of KC_MS_WH_DOWN
  "KC_WH_L", // alias of KC_MS_WH_LEFT
  "KC_WH_R", // alias of KC_MS_WH_RIGHT
  "KC_ACL0", // alias of KC_MS_ACCEL0
  "KC_ACL1", // alias of KC_MS_ACCEL1
  "KC_ACL2", // alias of KC_MS_ACCEL2
  "KC_LCTL", // alias of KC_LEFT_CTRL
  "KC_LSFT", // alias of KC_LEFT_SHIFT
  "KC_LALT", // alias of KC_LEFT_ALT
  "KC_LOPT", // alias of KC_LEFT_ALT
  "KC_LGUI", // alias of KC_LEFT_GUI
  "KC_LCMD", // alias of KC_LEFT_GUI
  "KC_LWIN", // alias of KC_LEFT_GUI
  "KC_RCTL", // alias of KC_RIGHT_CTRL
  "KC_RSFT", // alias of KC_RIGHT_SHIFT
  "KC_RALT", // alias of KC_RIGHT_ALT
  "KC_ROPT", // alias of KC_RIGHT_ALT
  "KC_ALGR", // alias of KC_RIGHT_ALT
  "KC_RGUI", // alias of KC_RIGHT_GUI
  "KC_RCMD", // alias of KC_RIGHT_GUI
  "KC_RWIN", // alias of KC_RIGHT_GUI
  "SH_TOGG", // alias of QK_SWAP_HANDS_TOGGLE
  "SH_TT", // alias of QK_SWAP_HANDS_TAP_TOGGLE
  "SH_MON", // alias of QK_SWAP_HANDS_MOMENTARY_ON
  "SH_MOFF", // alias of QK_SWAP_HANDS_MOMENTARY_OFF
  "SH_OFF", // alias of QK_SWAP_HANDS_OFF
  "SH_ON", // alias of QK_SWAP_HANDS_ON
  "SH_OS", // alias of QK_SWAP_HANDS_ONE_SHOT
  "CL_SWAP", // alias of QK_MAGIC_SWAP_CONTROL_CAPS_LOCK
  "CL_NORM", // alias of QK_MAGIC_UNSWAP_CONTROL_CAPS_LOCK
  "CL_TOGG", // alias of QK_MAGIC_TOGGLE_CONTROL_CAPS_LOCK
  "CL_CAPS", // alias of QK_MAGIC_CAPS_LOCK_AS_CONTROL_OFF
  "CL_CTRL", // alias of QK_MAGIC_CAPS_LOCK_AS_CONTROL_ON
  "AG_LSWP", // alias of QK_MAGIC_SWAP_LALT_LGUI
  "AG_LNRM", // alias of QK_MAGIC_UNSWAP_LALT_LGUI
  "AG_RSWP", // alias of QK_MAGIC_SWAP_RALT_RGUI
  "AG_RNRM", // alias of QK_MAGIC_UNSWAP_RALT_RGUI
  "GU_ON", // alias of QK_MAGIC_GUI_ON
  "GU_OFF", // alias of QK_MAGIC_GUI_OFF
  "GU_TOGG", // alias of QK_MAGIC_TOGGLE_GUI
  "GE_SWAP", // alias of QK_MAGIC_SWAP_GRAVE_ESC
  "GE_NORM", // alias of QK_MAGIC_UNSWAP_GRAVE_ESC
  "BS_SWAP", // alias of QK_MAGIC_SWAP_BACKSLASH_BACKSPACE
  "BS_NORM", // alias of QK_MAGIC_UNSWAP_BACKSLASH_BACKSPACE
  "BS_TOGG", // alias of QK_MAGIC_TOGGLE_BACKSLASH_BACKSPACE
  "NK_ON", // alias of QK_MAGIC_NKRO_ON
  "NK_OFF", // alias of QK_MAGIC_NKRO_OFF
  "NK_TOGG", // alias of QK_MAGIC_TOGGLE_NKRO
  "AG_SWAP", // alias of QK_MAGIC_SWAP_ALT_GUI
  "AG_NORM", // alias of QK_MAGIC_UNSWAP_ALT_GUI
  "AG_TOGG", // alias of QK_MAGIC_TOGGLE_ALT_GUI
  "CG_LSWP", // alias of QK_MAGIC_SWAP_LCTL_LGUI
  "CG_LNRM", // alias of QK_MAGIC_UNSWAP_LCTL_LGUI
  "CG_RSWP", // alias of QK_MAGIC_SWAP_RCTL_RGUI
  "CG_RNRM", // alias of QK_MAGIC_UNSWAP_RCTL_RGUI
  "CG_SWAP", // alias of QK_MAGIC_SWAP_CTL_GUI
  "CG_NORM", // alias of QK_MAGIC_UNSWAP_CTL_GUI
  "CG_TOGG", // alias of QK_MAGIC_TOGGLE_CTL_GUI
  "EH_LEFT", // alias of QK_MAGIC_EE_HANDS_LEFT
  "EH_RGHT", // alias of QK_MAGIC_EE_HANDS_RIGHT
  "EC_SWAP", // alias of QK_MAGIC_SWAP_ESCAPE_CAPS_LOCK
  "EC_NORM", // alias of QK_MAGIC_UNSWAP_ESCAPE_CAPS_LOCK
  "EC_TOGG", // alias of QK_MAGIC_TOGGLE_ESCAPE_CAPS_LOCK
  "MI_ON", // alias of QK_MIDI_ON
  "MI_OFF", // alias of QK_MIDI_OFF
  "MI_TOGG", // alias of QK_MIDI_TOGGLE
  "MI_C", // alias of QK_MIDI_NOTE_C_0
  "MI_Cs", // alias of QK_MIDI_NOTE_C_SHARP_0
  "MI_Db", // alias of QK_MIDI_NOTE_C_SHARP_0
  "MI_D", // alias of QK_MIDI_NOTE_D_0
  "MI_Ds", // alias of QK_MIDI_NOTE_D_SHARP_0
  "MI_Eb", // alias of QK_MIDI_NOTE_D_SHARP_0
  "MI_E", // alias of QK_MIDI_NOTE_E_0
  "MI_F", // alias of QK_MIDI_NOTE_F_0
  "MI_Fs", // alias of QK_MIDI_NOTE_F_SHARP_0
  "MI_Gb", // alias of QK_MIDI_NOTE_F_SHARP_0
  "MI_G", // alias of QK_MIDI_NOTE_G_0
  "MI_Gs", // alias of QK_MIDI_NOTE_G_SHARP_0
  "MI_Ab", // alias of QK_MIDI_NOTE_G_SHARP_0
  "MI_A", // alias of QK_MIDI_NOTE_A_0
  "MI_As", // alias of QK_MIDI_NOTE_A_SHARP_0
  "MI_Bb", // alias of QK_MIDI_NOTE_A_SHARP_0
  "MI_B", // alias of QK_MIDI_NOTE_B_0
  "MI_C1", // alias of QK_MIDI_NOTE_C_1
  "MI_Cs1", // alias of QK_MIDI_NOTE_C_SHARP_1
  "MI_Db1", // alias of QK_MIDI_NOTE_C_SHARP_1
  "MI_D1", // alias of QK_MIDI_NOTE_D_1
  "MI_Ds1", // alias of QK_MIDI_NOTE_D_SHARP_1
  "MI_Eb1", // alias of QK_MIDI_NOTE_D_SHARP_1
  "MI_E1", // alias of QK_MIDI_NOTE_E_1
  "MI_F1", // alias of QK_MIDI_NOTE_F_1
  "MI_Fs1", // alias of QK_MIDI_NOTE_F_SHARP_1
  "MI_Gb1", // alias of QK_MIDI_NOTE_F_SHARP_1
  "MI_G1", // alias of QK_MIDI_NOTE_G_1
  "MI_Gs1", // alias of QK_MIDI_NOTE_G_SHARP_1
  "MI_Ab1", // alias of QK_MIDI_NOTE_G_SHARP_1
  "MI_A1", // alias of QK_MIDI_NOTE_A_1
  "MI_As1", // alias of QK_MIDI_NOTE_A_SHARP_1
  "MI_Bb1", // alias of QK_MIDI_NOTE_A_SHARP_1
  "MI_B1", // alias of QK_MIDI_NOTE_B_1
  "MI_C2", // alias of QK_MIDI_NOTE_C_2
  "MI_Cs2", // alias of QK_MIDI_NOTE_C_SHARP_2
  "MI_Db2", // alias of QK_MIDI_NOTE_C_SHARP_2
  "MI_D2", // alias of QK_MIDI_NOTE_D_2
  "MI_Ds2", // alias of QK_MIDI_NOTE_D_SHARP_2
  "MI_Eb2", // alias of QK_MIDI_NOTE_D_SHARP_2
  "MI_E2", // alias of QK_MIDI_NOTE_E_2
  "MI_F2", // alias of QK_MIDI_NOTE_F_2
  "MI_Fs2", // alias of QK_MIDI_NOTE_F_SHARP_2
  "MI_Gb2", // alias of QK_MIDI_NOTE_F_SHARP_2
  "MI_G2", // alias of QK_MIDI_NOTE_G_2
  "MI_Gs2", // alias of QK_MIDI_NOTE_G_SHARP_2
  "MI_Ab2", // alias of QK_MIDI_NOTE_G_SHARP_2
  "MI_A2", // alias of QK_MIDI_NOTE_A_2
  "MI_As2", // alias of QK_MIDI_NOTE_A_SHARP_2
  "MI_Bb2", // alias of QK_MIDI_NOTE_A_SHARP_2
  "MI_B2", // alias of QK_MIDI_NOTE_B_2
  "MI_C3", // alias of QK_MIDI_NOTE_C_3
  "MI_Cs3", // alias of QK_MIDI_NOTE_C_SHARP_3
  "MI_Db3", // alias of QK_MIDI_NOTE_C_SHARP_3
  "MI_D3", // alias of QK_MIDI_NOTE_D_3
  "MI_Ds3", // alias of QK_MIDI_NOTE_D_SHARP_3
  "MI_Eb3", // alias of QK_MIDI_NOTE_D_SHARP_3
  "MI_E3", // alias of QK_MIDI_NOTE_E_3
  "MI_F3", // alias of QK_MIDI_NOTE_F_3
  "MI_Fs3", // alias of QK_MIDI_NOTE_F_SHARP_3
  "MI_Gb3", // alias of QK_MIDI_NOTE_F_SHARP_3
  "MI_G3", // alias of QK_MIDI_NOTE_G_3
  "MI_Gs3", // alias of QK_MIDI_NOTE_G_SHARP_3
  "MI_Ab3", // alias of QK_MIDI_NOTE_G_SHARP_3
  "MI_A3", // alias of QK_MIDI_NOTE_A_3
  "MI_As3", // alias of QK_MIDI_NOTE_A_SHARP_3
  "MI_Bb3", // alias of QK_MIDI_NOTE_A_SHARP_3
  "MI_B3", // alias of QK_MIDI_NOTE_B_3
  "MI_C4", // alias of QK_MIDI_NOTE_C_4
  "MI_Cs4", // alias of QK_MIDI_NOTE_C_SHARP_4
  "MI_Db4", // alias of QK_MIDI_NOTE_C_SHARP_4
  "MI_D4", // alias of QK_MIDI_NOTE_D_4
  "MI_Ds4", // alias of QK_MIDI_NOTE_D_SHARP_4
  "MI_Eb4", // alias of QK_MIDI_NOTE_D_SHARP_4
  "MI_E4", // alias of QK_MIDI_NOTE_E_4
  "MI_F4", // alias of QK_MIDI_NOTE_F_4
  "MI_Fs4", // alias of QK_MIDI_NOTE_F_SHARP_4
  "MI_Gb4", // alias of QK_MIDI_NOTE_F_SHARP_4
  "MI_G4", // alias of QK_MIDI_NOTE_G_4
  "MI_Gs4", // alias of QK_MIDI_NOTE_G_SHARP_4
  "MI_Ab4", // alias of QK_MIDI_NOTE_G_SHARP_4
  "MI_A4", // alias of QK_MIDI_NOTE_A_4
  "MI_As4", // alias of QK_MIDI_NOTE_A_SHARP_4
  "MI_Bb4", // alias of QK_MIDI_NOTE_A_SHARP_4
  "MI_B4", // alias of QK_MIDI_NOTE_B_4
  "MI_C5", // alias of QK_MIDI_NOTE_C_5
  "MI_Cs5", // alias of QK_MIDI_NOTE_C_SHARP_5
  "MI_Db5", // alias of QK_MIDI_NOTE_C_SHARP_5
  "MI_D5", // alias of QK_MIDI_NOTE_D_5
  "MI_Ds5", // alias of QK_MIDI_NOTE_D_SHARP_5
  "MI_Eb5", // alias of QK_MIDI_NOTE_D_SHARP_5
  "MI_E5", // alias of QK_MIDI_NOTE_E_5
  "MI_F5", // alias of QK_MIDI_NOTE_F_5
  "MI_Fs5", // alias of QK_MIDI_NOTE_F_SHARP_5
  "MI_Gb5", // alias of QK_MIDI_NOTE_F_SHARP_5
  "MI_G5", // alias of QK_MIDI_NOTE_G_5
  "MI_Gs5", // alias of QK_MIDI_NOTE_G_SHARP_5
  "MI_Ab5", // alias of QK_MIDI_NOTE_G_SHARP_5
  "MI_A5", // alias of QK_MIDI_NOTE_A_5
  "MI_As5", // alias of QK_MIDI_NOTE_A_SHARP_5
  "MI_Bb5", // alias of QK_MIDI_NOTE_A_SHARP_5
  "MI_B5", // alias of QK_MIDI_NOTE_B_5
  "MI_OCN2", // alias of QK_MIDI_OCTAVE_N2
  "MI_OCN1", // alias of QK_MIDI_OCTAVE_N1
  "MI_OC0", // alias of QK_MIDI_OCTAVE_0
  "MI_OC1", // alias of QK_MIDI_OCTAVE_1
  "MI_OC2", // alias of QK_MIDI_OCTAVE_2
  "MI_OC3", // alias of QK_MIDI_OCTAVE_3
  "MI_OC4", // alias of QK_MIDI_OCTAVE_4
  "MI_OC5", // alias of QK_MIDI_OCTAVE_5
  "MI_OC6", // alias of QK_MIDI_OCTAVE_6
  "MI_OC7", // alias of QK_MIDI_OCTAVE_7
  "MI_OCTD", // alias of QK_MIDI_OCTAVE_DOWN
  "MI_OCTU", // alias of QK_MIDI_OCTAVE_UP
  "MI_TRN6", // alias of QK_MIDI_TRANSPOSE_N6
  "MI_TRN5", // alias of QK_MIDI_TRANSPOSE_N5
  "MI_TRN4", // alias of QK_MIDI_TRANSPOSE_N4
  "MI_TRN3", // alias of QK_MIDI_TRANSPOSE_N3
  "MI_TRN2", // alias of QK_MIDI_TRANSPOSE_N2
  "MI_TRN1", // alias of QK_MIDI_TRANSPOSE_N1
  "MI_TR0", // alias of QK_MIDI_TRANSPOSE_0
  "MI_TR1", // alias of QK_MIDI_TRANSPOSE_1
  "MI_TR2", // alias of QK_MIDI_TRANSPOSE_2
  "MI_TR3", // alias of QK_MIDI_TRANSPOSE_3
  "MI_TR4", // alias of QK_MIDI_TRANSPOSE_4
  "MI_TR5", // alias of QK_MIDI_TRANSPOSE_5
  "MI_TR6", // alias of QK_MIDI_TRANSPOSE_6
  "MI_TRSD", // alias of QK_MIDI_TRANSPOSE_DOWN
  "MI_TRSU", // alias of QK_MIDI_TRANSPOSE_UP
  "MI_VL0", // alias of QK_MIDI_VELOCITY_0
  "MI_VL1", // alias of QK_MIDI_VELOCITY_1
  "MI_VL2", // alias of QK_MIDI_VELOCITY_2
  "MI_VL3", // alias of QK_MIDI_VELOCITY_3
  "MI_VL4", // alias of QK_MIDI_VELOCITY_4
  "MI_VL5", // alias of QK_MIDI_VELOCITY_5
  "MI_VL6", // alias of QK_MIDI_VELOCITY_6
  "MI_VL7", // alias of QK_MIDI_VELOCITY_7
  "MI_VL8", // alias of QK_MIDI_VELOCITY_8
  "MI_VL9", // alias of QK_MIDI_VELOCITY_9
  "MI_VL10", // alias of QK_MIDI_VELOCITY_10
  "MI_VELD", // alias of QK_MIDI_VELOCITY_DOWN
  "MI_VELU", // alias of QK_MIDI_VELOCITY_UP
  "MI_CH1", // alias of QK_MIDI_CHANNEL_1
  "MI_CH2", // alias of QK_MIDI_CHANNEL_2
  "MI_CH3", // alias of QK_MIDI_CHANNEL_3
  "MI_CH4", // alias of QK_MIDI_CHANNEL_4
  "MI_CH5", // alias of QK_MIDI_CHANNEL_5
  "MI_CH6", // alias of QK_MIDI_CHANNEL_6
  "MI_CH7", // alias of QK_MIDI_CHANNEL_7
  "MI_CH8", // alias of QK_MIDI_CHANNEL_8
  "MI_CH9", // alias of QK_MIDI_CHANNEL_9
  "MI_CH10", // alias of QK_MIDI_CHANNEL_10
  "MI_CH11", // alias of QK_MIDI_CHANNEL_11
  "MI_CH12", // alias of QK_MIDI_CHANNEL_12
  "MI_CH13", // alias of QK_MIDI_CHANNEL_13
  "MI_CH14", // alias of QK_MIDI_CHANNEL_14
  "MI_CH15", // alias of QK_MIDI_CHANNEL_15
  "MI_CH16", // alias of QK_MIDI_CHANNEL_16
  "MI_CHND", // alias of QK_MIDI_CHANNEL_DOWN
  "MI_CHNU", // alias of QK_MIDI_CHANNEL_UP
  "MI_AOFF", // alias of QK_MIDI_ALL_NOTES_OFF
  "MI_SUST", // alias of QK_MIDI_SUSTAIN
  "MI_PORT", // alias of QK_MIDI_PORTAMENTO
  "MI_SOST", // alias of QK_MIDI_SOSTENUTO
  "MI_SOFT", // alias of QK_MIDI_SOFT
  "MI_LEG", // alias of QK_MIDI_LEGATO
  "MI_MOD", // alias of QK_MIDI_MODULATION
  "MI_MODD", // alias of QK_MIDI_MODULATION_SPEED_DOWN
  "MI_MODU", // alias of QK_MIDI_MODULATION_SPEED_UP
  "MI_BNDD", // alias of QK_MIDI_PITCH_BEND_DOWN
  "MI_BNDU", // alias of QK_MIDI_PITCH_BEND_UP
  "SQ_ON", // alias of QK_SEQUENCER_ON
  "SQ_OFF", // alias of QK_SEQUENCER_OFF
  "SQ_TOGG", // alias of QK_SEQUENCER_TOGGLE
  "SQ_TMPD", // alias of QK_SEQUENCER_TEMPO_DOWN
  "SQ_TMPU", // alias of QK_SEQUENCER_TEMPO_UP
  "SQ_RESD", // alias of QK_SEQUENCER_RESOLUTION_DOWN
  "SQ_RESU", // alias of QK_SEQUENCER_RESOLUTION_UP
  "SQ_SALL", // alias of QK_SEQUENCER_STEPS_ALL
  "SQ_SCLR", // alias of QK_SEQUENCER_STEPS_CLEAR
  "JS_0", // alias of QK_JOYSTICK_BUTTON_0
  "JS_1", // alias of QK_JOYSTICK_BUTTON_1
  "JS_2", // alias of QK_JOYSTICK_BUTTON_2
  "JS_3", // alias of QK_JOYSTICK_BUTTON_3
  "JS_4", // alias of QK_JOYSTICK_BUTTON_4
  "JS_5", // alias of QK_JOYSTICK_BUTTON_5
  "JS_6", // alias of QK_JOYSTICK_BUTTON_6
  "JS_7", // alias of QK_JOYSTICK_BUTTON_7
  "JS_8", // alias of QK_JOYSTICK_BUTTON_8
  "JS_9", // alias of QK_JOYSTICK_BUTTON_9
  "JS_10", // alias of QK_JOYSTICK_BUTTON_10
  "JS_11", // alias of QK_JOYSTICK_BUTTON_11
  "JS_12", // alias of QK_JOYSTICK_BUTTON_12
  "JS_13", // alias of QK_JOYSTICK_BUTTON_13
  "JS_14", // alias of QK_JOYSTICK_BUTTON_14
  "JS_15", // alias of QK_JOYSTICK_BUTTON_15
  "JS_16", // alias of QK_JOYSTICK_BUTTON_16
  "JS_17", // alias of QK_JOYSTICK_BUTTON_17
  "JS_18", // alias of QK_JOYSTICK_BUTTON_18
  "JS_19", // alias of QK_JOYSTICK_BUTTON_19
  "JS_20", // alias of QK_JOYSTICK_BUTTON_20
  "JS_21", // alias of QK_JOYSTICK_BUTTON_21
  "JS_22", // alias of QK_JOYSTICK_BUTTON_22
  "JS_23", // alias of QK_JOYSTICK_BUTTON_23
  "JS_24", // alias of QK_JOYSTICK_BUTTON_24
  "JS_25", // alias of QK_JOYSTICK_BUTTON_25
  "JS_26", // alias of QK_JOYSTICK_BUTTON_26
  "JS_27", // alias of QK_JOYSTICK_BUTTON_27
  "JS_28", // alias of QK_JOYSTICK_BUTTON_28
  "JS_29", // alias of QK_JOYSTICK_BUTTON_29
  "JS_30", // alias of QK_JOYSTICK_BUTTON_30
  "JS_31", // alias of QK_JOYSTICK_BUTTON_31
  "PB_1", // alias of QK_PROGRAMMABLE_BUTTON_1
  "PB_2", // alias of QK_PROGRAMMABLE_BUTTON_2
  "PB_3", // alias of QK_PROGRAMMABLE_BUTTON_3
  "PB_4", // alias of QK_PROGRAMMABLE_BUTTON_4
  "PB_5", // alias of QK_PROGRAMMABLE_BUTTON_5
  "PB_6", // alias of QK_PROGRAMMABLE_BUTTON_6
  "PB_7", // alias of QK_PROGRAMMABLE_BUTTON_7
  "PB_8", // alias of QK_PROGRAMMABLE_BUTTON_8
  "PB_9", // alias of QK_PROGRAMMABLE_BUTTON_9
  "PB_10", // alias of QK_PROGRAMMABLE_BUTTON_10
  "PB_11", // alias of QK_PROGRAMMABLE_BUTTON_11
  "PB_12", // alias of QK_PROGRAMMABLE_BUTTON_12
  "PB_13", // alias of QK_PROGRAMMABLE_BUTTON_13
  "PB_14", // alias of QK_PROGRAMMABLE_BUTTON_14
  "PB_15", // alias of QK_PROGRAMMABLE_BUTTON_15
  "PB_16", // alias of QK_PROGRAMMABLE_BUTTON_16
  "PB_17", // alias of QK_PROGRAMMABLE_BUTTON_17
  "PB_18", // alias of QK_PROGRAMMABLE_BUTTON_18
  "PB_19", // alias of QK_PROGRAMMABLE_BUTTON_19
  "PB_20", // alias of QK_PROGRAMMABLE_BUTTON_20
  "PB_21", // alias of QK_PROGRAMMABLE_BUTTON_21
  "PB_22", // alias of QK_PROGRAMMABLE_BUTTON_22
  "PB_23", // alias of QK_PROGRAMMABLE_BUTTON_23
  "PB_24", // alias of QK_PROGRAMMABLE_BUTTON_24
  "PB_25", // alias of QK_PROGRAMMABLE_BUTTON_25
  "PB_26", // alias of QK_PROGRAMMABLE_BUTTON_26
  "PB_27", // alias of QK_PROGRAMMABLE_BUTTON_27
  "PB_28", // alias of QK_PROGRAMMABLE_BUTTON_28
  "PB_29", // alias of QK_PROGRAMMABLE_BUTTON_29
  "PB_30", // alias of QK_PROGRAMMABLE_BUTTON_30
  "PB_31", // alias of QK_PROGRAMMABLE_BUTTON_31
  "PB_32", // alias of QK_PROGRAMMABLE_BUTTON_32
  "AU_ON", // alias of QK_AUDIO_ON
  "AU_OFF", // alias of QK_AUDIO_OFF
  "AU_TOGG", // alias of QK_AUDIO_TOGGLE
  "CK_TOGG", // alias of QK_AUDIO_CLICKY_TOGGLE
  "CK_ON", // alias of QK_AUDIO_CLICKY_ON
  "CK_OFF", // alias of QK_AUDIO_CLICKY_OFF
  "CK_UP", // alias of QK_AUDIO_CLICKY_UP
  "CK_DOWN", // alias of QK_AUDIO_CLICKY_DOWN
  "CK_RST", // alias of QK_AUDIO_CLICKY_RESET
  "MU_ON", // alias of QK_MUSIC_ON
  "MU_OFF", // alias of QK_MUSIC_OFF
  "MU_TOGG", // alias of QK_MUSIC_TOGGLE
  "MU_NEXT", // alias of QK_MUSIC_MODE_NEXT
  "AU_NEXT", // alias of QK_AUDIO_VOICE_NEXT
  "AU_PREV", // alias of QK_AUDIO_VOICE_PREVIOUS
  "MC_0", // alias of QK_MACRO_0
  "MC_1", // alias of QK_MACRO_1
  "MC_2", // alias of QK_MACRO_2
  "MC_3", // alias of QK_MACRO_3
  "MC_4", // alias of QK_MACRO_4
  "MC_5", // alias of QK_MACRO_5
  "MC_6", // alias of QK_MACRO_6
  "MC_7", // alias of QK_MACRO_7
  "MC_8", // alias of QK_MACRO_8
  "MC_9", // alias of QK_MACRO_9
  "MC_10", // alias of QK_MACRO_10
  "MC_11", // alias of QK_MACRO_11
  "MC_12", // alias of QK_MACRO_12
  "MC_13", // alias of QK_MACRO_13
  "MC_14", // alias of QK_MACRO_14
  "MC_15", // alias of QK_MACRO_15
  "MC_16", // alias of QK_MACRO_16
  "MC_17", // alias of QK_MACRO_17
  "MC_18", // alias of QK_MACRO_18
  "MC_19", // alias of QK_MACRO_19
  "MC_20", // alias of QK_MACRO_20
  "MC_21", // alias of QK_MACRO_21
  "MC_22", // alias of QK_MACRO_22
  "MC_23", // alias of QK_MACRO_23
  "MC_24", // alias of QK_MACRO_24
  "MC_25", // alias of QK_MACRO_25
  "MC_26", // alias of QK_MACRO_26
  "MC_27", // alias of QK_MACRO_27
  "MC_28", // alias of QK_MACRO_28
  "MC_29", // alias of QK_MACRO_29
  "MC_30", // alias of QK_MACRO_30
  "MC_31", // alias of QK_MACRO_31
  "BL_ON", // alias of QK_BACKLIGHT_ON
  "BL_OFF", // alias of QK_BACKLIGHT_OFF
  "BL_TOGG", // alias of QK_BACKLIGHT_TOGGLE
  "BL_DOWN", // alias of QK_BACKLIGHT_DOWN
  "BL_UP", // alias of QK_BACKLIGHT_UP
  "BL_STEP", // alias of QK_BACKLIGHT_STEP
  "BL_BRTG", // alias of QK_BACKLIGHT_TOGGLE_BREATHING
  "RGB_MOD", // alias of RGB_MODE_FORWARD
  "RGB_RMOD", // alias of RGB_MODE_REVERSE
  "RGB_M_P", // alias of RGB_MODE_PLAIN
  "RGB_M_B", // alias of RGB_MODE_BREATHE
  "RGB_M_R", // alias of RGB_MODE_RAINBOW
  "RGB_M_SW", // alias of RGB_MODE_SWIRL
  "RGB_M_SN", // alias of RGB_MODE_SNAKE
  "RGB_M_K", // alias of RGB_MODE_KNIGHT
  "RGB_M_X", // alias of RGB_MODE_XMAS
  "RGB_M_G", // alias of RGB_MODE_GRADIENT
  "RGB_M_T", // alias of RGB_MODE_RGBTEST
  "RGB_M_TW", // alias of RGB_MODE_TWINKLE
  "QK_BOOT", // alias of QK_BOOTLOADER
  "QK_RBT", // alias of QK_REBOOT
  "DB_TOGG", // alias of QK_DEBUG_TOGGLE
  "EE_CLR", // alias of QK_CLEAR_EEPROM
  "AS_DOWN", // alias of QK_AUTO_SHIFT_DOWN
  "AS_UP", // alias of QK_AUTO_SHIFT_UP
  "AS_RPT", // alias of QK_AUTO_SHIFT_REPORT
  "AS_ON", // alias of QK_AUTO_SHIFT_ON
  "AS_OFF", // alias of QK_AUTO_SHIFT_OFF
  "AS_TOGG", // alias of QK_AUTO_SHIFT_TOGGLE
  "QK_GESC", // alias of QK_GRAVE_ESCAPE
  "VK_TOGG", // alias of QK_VELOCIKEY_TOGGLE
  "SC_LCPO", // alias of QK_SPACE_CADET_LEFT_CTRL_PARENTHESIS_OPEN
  "SC_RCPC", // alias of QK_SPACE_CADET_RIGHT_CTRL_PARENTHESIS_CLOSE
  "SC_LSPO", // alias of QK_SPACE_CADET_LEFT_SHIFT_PARENTHESIS_OPEN
  "SC_RSPC", // alias of QK_SPACE_CADET_RIGHT_SHIFT_PARENTHESIS_CLOSE
  "SC_LAPO", // alias of QK_SPACE_CADET_LEFT_ALT_PARENTHESIS_OPEN
  "SC_RAPC", // alias of QK_SPACE_CADET_RIGHT_ALT_PARENTHESIS_CLOSE
  "SC_SENT", // alias of QK_SPACE_CADET_RIGHT_SHIFT_ENTER
  "OU_AUTO", // alias of QK_OUTPUT_AUTO
  "OU_USB", // alias of QK_OUTPUT_USB
  "OU_BT", // alias of QK_OUTPUT_BLUETOOTH
  "UC_NEXT", // alias of QK_UNICODE_MODE_NEXT
  "UC_PREV", // alias of QK_UNICODE_MODE_PREVIOUS
  "UC_MAC", // alias of QK_UNICODE_MODE_MACOS
  "UC_LINX", // alias of QK_UNICODE_MODE_LINUX
  "UC_WIN", // alias of QK_UNICODE_MODE_WINDOWS
  "UC_BSD", // alias of QK_UNICODE_MODE_BSD
  "UC_WINC", // alias of QK_UNICODE_MODE_WINCOMPOSE
  "UC_EMAC", // alias of QK_UNICODE_MODE_EMACS
  "HF_ON", // alias of QK_HAPTIC_ON
  "HF_OFF", // alias of QK_HAPTIC_OFF
  "HF_TOGG", // alias of QK_HAPTIC_TOGGLE
  "HF_RST", // alias of QK_HAPTIC_RESET
  "HF_FDBK", // alias of QK_HAPTIC_FEEDBACK_TOGGLE
  "HF_BUZZ", // alias of QK_HAPTIC_BUZZ_TOGGLE
  "HF_NEXT", // alias of QK_HAPTIC_MODE_NEXT
  "HF_PREV", // alias of QK_HAPTIC_MODE_PREVIOUS
  "HF_CONT", // alias of QK_HAPTIC_CONTINUOUS_TOGGLE
  "HF_CONU", // alias of QK_HAPTIC_CONTINUOUS_UP
  "HF_COND", // alias of QK_HAPTIC_CONTINUOUS_DOWN
  "HF_DWLU", // alias of QK_HAPTIC_DWELL_UP
  "HF_DWLD", // alias of QK_HAPTIC_DWELL_DOWN
  "CM_ON", // alias of QK_COMBO_ON
  "CM_OFF", // alias of QK_COMBO_OFF
  "CM_TOGG", // alias of QK_COMBO_TOGGLE
  "DM_REC1", // alias of QK_DYNAMIC_MACRO_RECORD_START_1
  "DM_REC2", // alias of QK_DYNAMIC_MACRO_RECORD_START_2
  "DM_RSTP", // alias of QK_DYNAMIC_MACRO_RECORD_STOP
  "DM_PLY1", // alias of QK_DYNAMIC_MACRO_PLAY_1
  "DM_PLY2", // alias of QK_DYNAMIC_MACRO_PLAY_2
  "QK_LEAD", // alias of QK_LEADER
  "OS_ON", // alias of QK_ONE_SHOT_ON
  "OS_OFF", // alias of QK_ONE_SHOT_OFF
  "OS_TOGG", // alias of QK_ONE_SHOT_TOGGLE
  "KO_TOGG", // alias of QK_KEY_OVERRIDE_TOGGLE
  "KO_ON", // alias of QK_KEY_OVERRIDE_ON
  "KO_OFF", // alias of QK_KEY_OVERRIDE_OFF
  "SE_LOCK", // alias of QK_SECURE_LOCK
  "SE_UNLK", // alias of QK_SECURE_UNLOCK
  "SE_TOGG", // alias of QK_SECURE_TOGGLE
  "SE_REQ", // alias of QK_SECURE_REQUEST
  "DT_PRNT", // alias of QK_DYNAMIC_TAPPING_TERM_PRINT
  "DT_UP", // alias of QK_DYNAMIC_TAPPING_TERM_UP
  "DT_DOWN", // alias of QK_DYNAMIC_TAPPING_TERM_DOWN
  "CW_TOGG", // alias of QK_CAPS_WORD_TOGGLE
  "AC_ON", // alias of QK_AUTOCORRECT_ON
  "AC_OFF", // alias of QK_AUTOCORRECT_OFF
  "AC_TOGG", // alias of QK_AUTOCORRECT_TOGGLE
  "TL_LOWR", // alias of QK_TRI_LAYER_LOWER
  "TL_UPPR", // alias of QK_TRI_LAYER_UPPER
  "QK_REP", // alias of QK_REPEAT_KEY
  "QK_AREP", // alias of QK_ALT_REPEAT_KEY
  "KC_TILD", // alias of S(KC_GRAVE) // ~
  "KC_EXLM", // alias of S(KC_1)    // !
  "KC_AT", // alias of   S(KC_2)    // @
  "KC_HASH", // alias of S(KC_3)    // #
  "KC_DLR", // alias of  S(KC_4)    // $
  "KC_PERC", // alias of S(KC_5)    // %
  "KC_CIRC", // alias of S(KC_6)    // ^
  "KC_AMPR", // alias of S(KC_7)    // &
  "KC_ASTR", // alias of S(KC_8)    // *
  "KC_LPRN", // alias of S(KC_9)    // (
  "KC_RPRN", // alias of S(KC_0)    // )
  "KC_UNDS", // alias of S(KC_MINUS) // _
  "KC_PLUS", // alias of S(KC_EQUAL) // +
  "KC_LCBR", // alias of S(KC_LEFT_BRACKET) // {
  "KC_RCBR", // alias of S(KC_RIGHT_BRACKET) // }
  "KC_PIPE", // alias of S(KC_BACKSLASH) // |
  "KC_COLN", // alias of S(KC_SEMICOLON) // :
  "KC_DQUO", // alias of S(KC_QUOTE) // "
  "KC_LABK", // alias of S(KC_COMMA) // <
  "KC_RABK", // alias of S(KC_DOT)  // >
  "KC_QUES", // alias of S(KC_SLASH) // ?
  "KC_TILDE", // alias of KC_TILD
  "KC_EXCLAIM", // alias of KC_EXLM
  "KC_DOLLAR", // alias of KC_DLR
  "KC_PERCENT", // alias of KC_PERC
  "KC_CIRCUMFLEX", // alias of KC_CIRC
  "KC_AMPERSAND", // alias of KC_AMPR
  "KC_ASTERISK", // alias of KC_ASTR
  "KC_LEFT_PAREN", // alias of KC_LPRN
  "KC_RIGHT_PAREN", // alias of KC_RPRN
  "KC_UNDERSCORE", // alias of KC_UNDS
  "KC_LEFT_CURLY_BRACE", // alias of KC_LCBR
  "KC_RIGHT_CURLY_BRACE", // alias of KC_RCBR
  "KC_COLON", // alias of KC_COLN
  "KC_DOUBLE_QUOTE", // alias of KC_DQUO
  "KC_DQT", // alias of KC_DQUO
  "KC_LEFT_ANGLE_BRACKET", // alias of KC_LABK
  "KC_LT", // alias of KC_LABK
  "KC_RIGHT_ANGLE_BRACKET", // alias of KC_RABK
  "KC_GT", // alias of KC_RABK
  "KC_QUESTION", // alias of KC_QUES
] as const

export type Keycode = typeof KEYCODES[number]

