#!/usr/bin/env bash

set -euo pipefail

KEYBOARDS=(
  keebio/iris/rev8
  keebio/sinc/rev3
  keebio/quefrency/rev4
  annepro2/c18
  hillside/46/0_1
)

function main() {
  ./install-symlinks

  if [ "${1:-}" == "all" ]; then
    qmk-compile "${KEYBOARDS[@]}"
  else
    kb="$(pick-keyboard "$@")"
    if [ -z "$kb" ]; then
      echo "No keyboard selected."
      exit 1
    fi
    qmk-compile "$kb"
  fi
}

function qmk-compile() {
  for kb in "$@"; do
    qmk compile -kb "$kb" -km elentok
    kb_basename="$(echo "$kb" | tr / _)"
    cp -f "$HOME/qmk_firmware/${kb_basename}_elentok".* ./binaries
  done
}

function pick-keyboard() {
  list-keyboards | filter "$@" | fzf-tmux -p --select-1
}

function list-keyboards() {
  for kb in "${KEYBOARDS[@]}"; do
    echo "$kb"
  done
}

function filter() {
  if [ $# -eq 0 ]; then
    cat
  else
    grep "$@"
  fi
}

main "$@"
