#!/usr/bin/env bash

set -euo pipefail

KEYBOARDS=(
  keebio/sinc/rev3
  keebio/quefrency/rev4
  annepro2/c18
)

./install-symlinks

if [ "${1:-}" == "all" ]; then
  for kb in "${KEYBOARDS[@]}"; do
    qmk compile -kb "$kb" -km elentok
  done
elif [ $# -gt 0 ]; then
  for kb in "$@"; do
    qmk compile -kb "$kb" -km elentok
  done
else
  kb="$(for kb in "${KEYBOARDS[@]}"; do echo "$kb"; done | fzf-tmux -p)"
  if [ -n "$kb" ]; then
    echo "> qmk compile -kb $kb -km elentok"
    qmk compile -kb "$kb" -km elentok
  fi
fi
