#!/usr/bin/env bash

set -euo pipefail

side="${1:-left}"

echo
echo "IMPORTANT: Double click the reset button to get the keyboard into bootloader mode"
echo

qmk flash -bl "uf2-split-$side" ./binaries/keebio_iris_rev8_elentok.uf2
