#!/usr/bin/env bash

set -euo pipefail

ROOT="$(dirname "${BASH_SOURCE[0]-$0}")"
ROOT="$(cd "$ROOT" && pwd)"

QMK_ROOT="$HOME/qmk_firmware"

echo "========================================"
echo "ROOT:     $ROOT"
echo "QMK ROOT: $QMK_ROOT"
echo
echo "Installing symlinks..."

if [ ! -e "$QMK_ROOT" ]; then
  echo "First setup QMK in ~/qmk_firmware"
  exit 1
fi

ln -sfT "$ROOT/elentok.h" "$QMK_ROOT/elentok.h"

if [ ! -e "$QMK_ROOT/keyboards/hillside/46-original" ]; then
  mv "$QMK_ROOT/keyboards/hillside/46" \
    "$QMK_ROOT/keyboards/hillside/46-original"
fi

ln -sfT "$ROOT/hillside46" "$QMK_ROOT/keyboards/hillside/46"

ln -sfT "$ROOT/quefrency-rev4" "$QMK_ROOT/keyboards/keebio/quefrency/keymaps/elentok"
ln -sfT "$ROOT/sinc-rev3" "$QMK_ROOT/keyboards/keebio/sinc/keymaps/elentok"

ln -sfT "$ROOT/annepro2/keymap" "$QMK_ROOT/keyboards/annepro2/keymaps/elentok"
ln -sfT "$ROOT/annepro2/c18-config.h" "$QMK_ROOT/keyboards/annepro2/c18/config.h"

echo "Done."
echo "========================================"
