#!/usr/bin/env bash

set -euo pipefail

echo 123

ROOT="$(dirname "${BASH_SOURCE[0]-$0}")"
ROOT="$(cd "$ROOT" && pwd)"

echo 456

QMK_ROOT="$HOME/qmk_firmware"

echo "ROOT:     $ROOT"
echo "QMK ROOT: $QMK_ROOT"
echo

if [ ! -e "$QMK_ROOT" ]; then
  echo "First setup QMK in ~/qmk_firmware"
  exit 1
fi

echo "ROOT=[$ROOT]"
echo "QMK_ROOT=[$QMK_ROOT]"

ln -sfT "$ROOT/quefrency-rev4" "$QMK_ROOT/keyboards/keebio/quefrency/keymaps/elentok"
ln -sfT "$ROOT/sinc-rev3" "$QMK_ROOT/keyboards/keebio/sinc/keymaps/elentok"

ln -sfT "$ROOT/annepro2/keymap" "$QMK_ROOT/keyboards/annepro2/keymaps/elentok"
ln -sfT "$ROOT/annepro2/c18-config.h" "$QMK_ROOT/keyboards/annepro2/c18/config.h"
